user default off

user erpapp on >StrongAppPassword ~cache:erp:* +@all
user readonly on >ReadOnlyPass ~cache:erp:* +@read +get +mget +exists +ttl
user metrics on >MetricsPass ~* +info +ping

maxmemory 512mb
maxmemory-policy allkeys-lru

loglevel notice