version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily" 
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot-starter"
        versions: ["2.x"]
    labels:
      - "chore"
      - "maven"

  - package-ecosystem: "github-actions"
    directory: "/" 
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "chore"
      - "github-actions"
