receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:9464"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]

    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug, prometheus ]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]