spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1080558841274-ju73rkqqh1vtagqst87iermlpd3s2e22.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
  cloud:
    openfeign:
      oauth2:
        enabled: true

  profiles:
    active: ${ACTIVE_PROFILE:dev}
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
      close-closeable: true
      flush-after-write-value: true
      write-date-keys-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    url:  jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSGRESQL_USERNAME}
    password: ${POSGRESQL_PASSWORD}
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 50         # Maximum number of connections in the pool
      minimum-idle: 10              # Minimum idle connections
      idle-timeout: 30000           # Time (ms) a connection is allowed to sit idle before being removed
      max-lifetime: 1800000         # Maximum lifetime of a connection (ms) (30 mins recommended)
      connection-timeout: 20000     # Maximum time (ms) to wait for a connection (20 seconds recommended)
      pool-name: HikariCP-Pool      # Custom pool name for better monitoring
      auto-commit: true             # Set to true if autocommit should be enabled by default
      validation-timeout: 5000      # Maximum time (ms) to wait for a connection validation
      leak-detection-threshold: 2000 # Log any connection usage over 2 seconds
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLInnoDBDialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: never
      continue-on-error: false
      schema-locations: classpath:data/schema.sql
      data-locations: classpath:data/data.sql
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
#  flyway:
#    baseline-version: true
#    enabled: true
#    user: ${POSGRESQL_USERNAME}
#    password: ${POSGRESQL_PASSWORD}
#    baseline-description: "init"
server:
  port: ${CONTAINER_PORT:8080}
  error:
    path: /user/error
    whitelabel:
      enabled: true

async:
  core-pool-size: 5
  max-pool-size: 20
  queue-capacity: 50
  keep-alive-seconds: 60
  wait-for-tasks-to-complete-on-shutdown: true
  rejected-execution-handler-policy: abort # Options: abort, callerruns, discard, discardoldest
