spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SSO_JWK_SET_URI:http://localhost:8180/auth/realms/ERP/protocol/openid-connect/certs}
      client:
        registration:
          nagerdate-technical-user:
            client-id: ${NAGERDATE_CLIENT_ID:erp}
            authorization-grant-type: ${NAGERDATE_AUTHORIZATION_GRANT_TYPE:password}
            provider: ${NAGERDATE_PROVIDER:nagerdate}
        provider:
          nagerdate:
            token-uri: ${NAGERDATE_SSO_JWT_TOKEN_URI:http://localhost:8180/auth/realms/ERP/protocol/openid-connect/token}
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
      close-closeable: true
      flush-after-write-value: true
      write-date-keys-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_JDBC_DRIVER}
  lifecycle:
    timeout-per-shutdown-phase: 1m
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jpa:
          compliance:
            transaction: true
            global_id_generation: true
            query_language: true
            fetch_plan: true
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    table: flyway_schema_history
    locations: ${FLYWAY_LOCATION:db/migration,db/importMigration}
    validate-on-migrate: true
    clean-disabled: true
  graphql:
    graphiql:
      enabled: true

sso:
  client-id: ${SSO_CLIENT_ID:erp}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}

management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
            server:
                requests: true
  endpoints:
    web:
      exposure:
        include: health, prometheus, info, loggers, threaddump
      base-path: /status
    access:
      default: read_only
  endpoint:
    health:
      probes:
        enabled: true
      access:
    prometheus:
      access: read_only
    info:
      access: read_only
    loggers:
      access: read_only
    threaddump:
      access: read_only
  server:
    port: 8090

server:
  forward-headers-strategy: native
  servlet:
    context-path: /api
  compression:
    enabled: true
    min-response-size: 2048
  port: 8080
  error:
    path: /user/error
    whitelabel:
      enabled: true
  http2:
    enabled: true
  shutdown: graceful

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ${LOG_LEVEL:INFO}
    org.springframework.security: TRACE
    org.springframework.web.client.RestTemplate: DEBUG
    org.keycloak.adapters: DEBUG
    org.springframework.security.oauth2.client: TRACE
    org.springframework.security.oauth2.client.web: TRACE
    org.springframework.security.oauth2.core.endpoint: TRACE
    org.springframework.security.oauth2.client.registration: TRACE
    org.springframework.transaction.support.TransactionSynchronizationManager: DEBUG
    org.springframework.transaction: DEBUG
    org:
      springframework:
        core:
          task: TRACE
      hibernate:
        stat: DEBUG
        engine:
          transaction: DEBUG
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE

async:
  core-pool-size: 10
  max-pool-size: 20
  queue-capacity: 50
  keep-alive-seconds: 60
  wait-for-tasks-to-complete-on-shutdown: true
  rejected-execution-handler-policy: abort # Options: abort, callerruns, discard, discardoldest
  phase: 10

# Feign client configurations
feign:
  client:
    nagerdate:
      registration-id: ${NAGERDATE_REGISTRATION_ID:nagerdate_technical_user}
      client-id: ${NAGERDATE_CLIENT_ID:erp}
      url: ${NAGERDATE_API_URL:https://date.nager.at}
      username: ${NAGERDATE_USERNAME:erp_adm}
      password: ${NAGERDATE_PASSWORD:secret}

otel:
  service:
    name: erp-customer-manager

  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  logs:
    exporter: otlp

  exporter:
    otlp:
      endpoint: http://localhost:4317
      protocol: grpc

  propagators: tracecontext,baggage