spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
      close-closeable: true
      flush-after-write-value: true
      write-date-keys-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    url:  jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSGRESQL_USERNAME}
    password: ${POSGRESQL_PASSWORD}
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLInnoDBDialect
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: never
      continue-on-error: false
      schema-locations: classpath:data/schema.sql
      data-locations: classpath:data/data.sql
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
#  flyway:
#    baseline-version: true
#    enabled: true
#    user: ${POSGRESQL_USERNAME}
#    password: ${POSGRESQL_PASSWORD}
#    baseline-description: "init"
server:
  port: ${CONTAINER_PORT:8080}
  error:
    path: /user/error
    whitelabel:
      enabled: true

async:
  core-pool-size: 5
  max-pool-size: 20
  queue-capacity: 50
  keep-alive-seconds: 60
  wait-for-tasks-to-complete-on-shutdown: true
  rejected-execution-handler-policy: abort # Options: abort, callerruns, discard, discardoldest