input {
  tcp {
    port => 15000
    codec => json_lines {
      charset => "UTF-8"
      decode_size_limit_bytes => 20971520
    }
    mode => "server"
    ssl_enabled => false
    tags => ["erp", "tcp"]
    add_field => { "source" => "tcp-input" }
  }
}

filter {
  # Timestamp field from log event
  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
    timezone => "UTC"
  }

  # structured log parsing
  json {
    source => "log-message"
    remove_field => ["log-message"]
  }

  # Parse fields
  mutate {
    add_field => {
      "environment" => "production"
      "application" => "erp-app"
    }
    # rename removed because log-message is removed by json{} above
    remove_field => ["@version", "host"]      # Remove unnecessary fields
  }

  # Add GeoIP info
  geoip {
    source => "client_ip"
    target => "[client][geoip]"
  }

  # Add tags
  if "_jsonparsefailure" in [tags] {
    mutate { add_tag => ["json_parse_error"] }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "erp-app-logs-%{+YYYY.MM.dd}"
    ssl_enabled  => false
    ilm_enabled => true
    ilm_policy => "erp-logs-policy"
    manage_template => true
    template_name => "erp-app-template"
    template_overwrite => true
    sniffing => true
    ssl_verification_mode => "none"
    timeout => 30
  }

  stdout {
    codec => rubydebug
  }
}
