name: "CI Build for Develop Branch"

on:
  pull_request:
    branches: [ "develop" ]
  push:
    branches: [ "develop" ]

jobs:
  build:
    name: Build Stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: BE Quality
        run: mvn clean install -P coverage

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
